@startuml
title Sequence Diagram for the `sortcom` command

actor User

box Logic #E6E6FA
participant ":LogicManager" as Logic
participant ":AddressBookParser" as ABParser
participant "cmd:SortComCommand" as Command
participant "result:CommandResult" as Result
end box

box Model #FFE4E1
participant "m:Model" as Model
end box

User -> Logic : execute("sortcom")
activate Logic

Logic -> ABParser : parseCommand("sortcom")
activate ABParser

create Command
ABParser -> Command
activate Command

ABParser <-- Command
deactivate Command

Logic <-- ABParser : cmd
deactivate ABParser

Logic -> Command : execute(m)
activate Command

Command -> Model : sort active contacts by company
activate Model
Model --> Command
deactivate Model

create Result
Command -> Result
activate Result
Result --> Command
deactivate Result

Logic <-- Command : result
deactivate Command

User <-- Logic : result
destroy Command
deactivate Logic

@enduml
