@startuml
title Activity: Create tag

start

:Execute `tag create`;

if () then ([tag name does not exist])
else ([else])
    :Show duplicate tag error;
    stop
endif

if () then ([colour provided])
    :Create tag with given colour;
else ([else])
    :Create tag with default colour;
endif

:Add tag to tag list;

stop
@enduml
