@startuml
title Activity: Restore contact

start

:Execute `restore`;

if () then ([valid index])
else ([else])
    :Show error message;
    stop
endif

:Retrieve deleted contact;

if () then ([not a duplicate contact])
else ([else])
    :Show error message;
    stop
endif

:Remove tags whose names no longer exist;
:Restore remaining tags using current tag definitions;
:Restore contact to main contact list;
:Remove contact from deleted contacts list;

stop
@enduml
